version: "3.9"
volumes:
  mongodata:

services:
  booklist:
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    container_name: "mongodb"
    volumes:
      - mongodata:/data/db